version: '2'

services:

  mongo:
    image: mongo
    container_name: mongo
    restart: unless-stopped
    volumes:
      - ./db:/data/db

  turtle:
    image: node:0.10-slim
    container_name: turtle
    restart: unless-stopped
    volumes:
      - $PWD:/app
    working_dir: /app
    command: node server.js
    ports:
      - 8070:8070
    depends_on:
      - mongo
