version: '2'

services:

  mongo:
    image: mongo
    container_name: mongo
    restart: unless-stopped
    volumes:
      - ./db:/data/db

  turtle:
    image: turtle-js
    container_name: turtle
    restart: unless-stopped
    ports:
      - 8070:8070
    depends_on:
      - mongo
